# Session 1 — Series & DataFrames

Runnable code for the **Build It** and **Experiment** sections.
Run each cell top to bottom.

In [1]:
import io

import numpy as np
import pandas as pd

print("pandas version:", pd.__version__)

pandas version: 3.0.3

## 1. Build It — Core Code

### 1.1 A Series from a list (default index)

In [2]:
sales = pd.Series([120, 340, 210])
sales

0    120
1    340
2    210
dtype: int64

### 1.2 A Series from a dict (keys become the index)

In [3]:
fruit = pd.Series({"apples": 3, "bananas": 5, "cherries": 7})
print("name :", fruit.name)
print("index:", list(fruit.index))
fruit

name : None
index: ['apples', 'bananas', 'cherries']

apples      3
bananas     5
cherries    7
dtype: int64

### 1.3 A Series with a custom index and a name

In [4]:
temps = pd.Series([21.5, 23.0, 19.8], index=["Mon", "Tue", "Wed"], name="temp_c")
print("name :", temps.name)
print("dtype:", temps.dtype)
print("Wed  :", temps["Wed"])
temps

name : temp_c
dtype: float64
Wed  : 19.8

Mon    21.5
Tue    23.0
Wed    19.8
Name: temp_c, dtype: float64

### 1.4 DataFrame from a dict of lists

In [5]:
df = pd.DataFrame(
    {
        "name": ["Ana", "Bo", "Cara", "Dan"],
        "score": [88, 92, 75, 60],
    }
)
df

   name  score
0   Ana     88
1    Bo     92
2  Cara     75
3   Dan     60

### 1.5 DataFrame from a list of dicts

In [6]:
rows = [
    {"name": "Ana", "score": 88},
    {"name": "Bo", "score": 92},
    {"name": "Cara"},  # missing score becomes NaN
]
pd.DataFrame(rows)

   name  score
0   Ana   88.0
1    Bo   92.0
2  Cara    NaN

### 1.6 DataFrame from CSV text via io.StringIO

In [7]:
csv_text = """name,score,city
Ana,88,Lisbon
Bo,92,Berlin
Cara,75,Paris
"""
csv_df = pd.read_csv(io.StringIO(csv_text))
csv_df

   name  score    city
0   Ana     88  Lisbon
1    Bo     92  Berlin
2  Cara     75   Paris

### 1.7 Inspecting a DataFrame

In [8]:
print("shape  :", df.shape)
print("columns:", list(df.columns))
print("index  :", list(df.index))
print("dtypes :")
print(df.dtypes)

shape  : (4, 2)
columns: ['name', 'score']
index  : [0, 1, 2, 3]
dtypes :
name       str
score    int64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   score   4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 208.0 bytes

### 1.8 head, tail, describe

In [10]:
print(df.head(2))
print()
print(df.tail(2))

  name  score
0  Ana     88
1   Bo     92

   name  score
2  Cara     75
3   Dan     60

In [11]:
df.describe()

          score
count   4.00000
mean   78.75000
std    14.45395
min    60.00000
25%    71.25000
50%    81.50000
75%    89.00000
max    92.00000

### 1.9 Selecting columns (single vs. multiple)

In [12]:
print("single column -> Series   :", type(df["score"]).__name__)
print("multiple cols -> DataFrame:", type(df[["name", "score"]]).__name__)
df[["name", "score"]]

single column -> Series   : Series
multiple cols -> DataFrame: DataFrame

   name  score
0   Ana     88
1    Bo     92
2  Cara     75
3   Dan     60

### 1.10 Adding and deriving columns

In [13]:
df["passed"] = df["score"] >= 60          # element-wise comparison
df["score_curve"] = df["score"] + 5       # arithmetic on the whole column
df

   name  score  passed  score_curve
0   Ana     88    True           93
1    Bo     92    True           97
2  Cara     75    True           80
3   Dan     60    True           65

## 2. Experiment

Change a parameter, predict the output, then run the cell.

**Experiment 1** — the index drives alignment, not position.

In [14]:
base = pd.DataFrame({"name": ["Ana", "Bo", "Cara"]}, index=[10, 20, 30])
extra = pd.Series([1.0, 2.0, 3.0], index=[30, 20, 10])
base["rank"] = extra          # aligned by label, so the order flips
base

    name  rank
10   Ana   3.0
20    Bo   2.0
30  Cara   1.0

**Experiment 2** — `describe()` ignores text unless you ask for everything.

In [15]:
print("numeric only:")
print(df.describe().columns.tolist())
print("\ninclude='all':")
print(df.describe(include="all").columns.tolist())

numeric only:
['score', 'score_curve']

include='all':
['name', 'score', 'passed', 'score_curve']

**Experiment 3** — Copy-on-Write: a slice does not mutate the parent.

In [16]:
original = pd.DataFrame({"x": [1, 2, 3]})
slice_view = original["x"]       # a view under CoW
original.loc[0, "x"] = 99        # safe, goes through .loc
print("original after .loc:", original["x"].tolist())
print("earlier slice is unchanged:", slice_view.tolist())

original after .loc: [99, 2, 3]
earlier slice is unchanged: [1, 2, 3]

**Experiment 4** — `head` and `tail` accept a row count.

In [17]:
big = pd.DataFrame({"n": range(10)})
print("head(3):", big.head(3)["n"].tolist())
print("tail(3):", big.tail(3)["n"].tolist())

head(3): [0, 1, 2]
tail(3): [7, 8, 9]

**Experiment 5** — a dict of lists with mismatched lengths fails loudly.

In [18]:
try:
    pd.DataFrame({"a": [1, 2, 3], "b": [1, 2]})
except ValueError as err:
    print("ValueError:", err)

ValueError: All arrays must be of the same length

## 3. Mini Project — Student Gradebook

In [19]:
students = pd.DataFrame(
    {
        "student": ["Ana", "Bo", "Cara", "Dan", "Eve"],
        "math": [91, 78, 84, 65, 88],
        "science": [89, 82, 79, 70, 95],
    }
)
students

  student  math  science
0     Ana    91       89
1      Bo    78       82
2    Cara    84       79
3     Dan    65       70
4     Eve    88       95

In [20]:
# Derive the average across the two numeric subjects (row-wise).
students["average"] = students[["math", "science"]].mean(axis=1)

### Map a helper function over a Series to produce letter grades.

In [21]:
def letter_grade(avg):
    if avg >= 90:
        return "A"
    if avg >= 80:
        return "B"
    if avg >= 70:
        return "C"
    return "F"


students["letter"] = students["average"].map(letter_grade)
students

  student  math  science  average letter
0     Ana    91       89     90.0      A
1      Bo    78       82     80.0      B
2    Cara    84       79     81.5      B
3     Dan    65       70     67.5      F
4     Eve    88       95     91.5      A

In [22]:
# Inspect the gradebook.
students.head()

  student  math  science  average letter
0     Ana    91       89     90.0      A
1      Bo    78       82     80.0      B
2    Cara    84       79     81.5      B
3     Dan    65       70     67.5      F
4     Eve    88       95     91.5      A

In [23]:
students.describe()

            math    science    average
count   5.000000   5.000000   5.000000
mean   81.200000  83.000000  82.100000
std    10.281051   9.565563   9.600781
min    65.000000  70.000000  67.500000
25%    78.000000  79.000000  80.000000
50%    84.000000  82.000000  81.500000
75%    88.000000  89.000000  90.000000
max    91.000000  95.000000  91.500000

In [24]:
# Only the columns we care about.
students[["student", "average"]]

  student  average
0     Ana     90.0
1      Bo     80.0
2    Cara     81.5
3     Dan     67.5
4     Eve     91.5

In [25]:
class_average = students["average"].mean()
passing = int((students["average"] >= 70).sum())
print(f"Class average : {class_average:.2f}")
print(f"Students >= 70: {passing} of {len(students)}")

Class average : 82.10
Students >= 70: 4 of 5