# ✅ Solutions — Session 2: Indexing, Selecting & Filtering

Worked answers to every exercise plus the **Sales Explorer** mini project.
Each solution is self-contained and uses pandas 3.x idioms only.

In [1]:
import pandas as pd

df = pd.DataFrame(
    {
        "city": ["Berlin", "Paris", "Berlin", "Lisbon", "Paris", "Berlin"],
        "price": [12.5, 30.0, 7.5, 22.0, 15.0, 40.0],
        "units": [120, 45, 300, 80, 200, 15],
    },
    index=["o1", "o2", "o3", "o4", "o5", "o6"],
)
df

      city  price  units
o1  Berlin   12.5    120
o2   Paris   30.0     45
o3  Berlin    7.5    300
o4  Lisbon   22.0     80
o5   Paris   15.0    200
o6  Berlin   40.0     15

## Exercise 1 — `.loc` vs `.iloc` on one value

**(Easy)** `"o3"` is the third label; it sits at position `2`, so `iloc[2, 1]` and `loc["o3", "price"]` agree.

In [2]:
by_label = df.loc["o3", "price"]
by_position = df.iloc[2, 1]
print("loc  :", by_label)
print("iloc :", by_position)
print("equal:", by_label == by_position)

loc  : 7.5
iloc : 7.5
equal: True

## Exercise 2 — Slices

**(Easy)** The `.loc` slice `"o2":"o4"` includes both endpoints (labels), while `.iloc[0:3]`
follows Python slicing and stops before position 3.

In [3]:
print("loc  o2..o4:", df.loc["o2":"o4"].index.tolist())
print("iloc 0..3  :", df.iloc[0:3].index.tolist())

loc  o2..o4: ['o2', 'o3', 'o4']
iloc 0..3  : ['o1', 'o2', 'o3']

## Exercise 3 — Combining conditions

**(Medium, coding)** Wrap each condition in parentheses and join them with `&` / `|`.

In [4]:
and_filter = df[(df["price"] > 15) & (df["units"] < 100)]
print("price > 15 AND units < 100:")
print(and_filter)

or_filter = df[df["city"].isin(["Berlin", "Lisbon"]) | (df["price"] < 10)]
print("\ncity in [Berlin, Lisbon] OR price < 10:")
print(or_filter)

price > 15 AND units < 100:
      city  price  units
o2   Paris   30.0     45
o4  Lisbon   22.0     80
o6  Berlin   40.0     15

city in [Berlin, Lisbon] OR price < 10:
      city  price  units
o1  Berlin   12.5    120
o3  Berlin    7.5    300
o4  Lisbon   22.0     80
o6  Berlin   40.0     15

## Exercise 4 — `between` and `query`, sorted by units descending

**(Medium)** `between(10, 25)` and `query("10 <= price <= 25")` select the same rows.

In [5]:
between_filter = df[df["price"].between(10, 25)]
print("between(10, 25):")
print(between_filter)

query_filter = df.query("10 <= price <= 25")
print("\nquery('10 <= price <= 25') matches:",
      between_filter.index.equals(query_filter.index))

sorted_result = between_filter.sort_values("units", ascending=False)
sorted_result

between(10, 25):
      city  price  units
o1  Berlin   12.5    120
o4  Lisbon   22.0     80
o5   Paris   15.0    200

query('10 <= price <= 25') matches: True

      city  price  units
o5   Paris   15.0    200
o1  Berlin   12.5    120
o4  Lisbon   22.0     80

## Exercise 5 — `.loc` assignment vs chained assignment

**(Advanced, conceptual)** `df.loc[mask, "status"] = "high"` targets the DataFrame itself, so it updates the parent.
`df["status"][mask] = "high"` first returns a temporary Series from `df["status"]` and
writes into *that* object; under Copy-on-Write the parent is left untouched.

In [6]:
demo = df.copy()
demo.loc[demo["price"] > 15, "status"] = "high"
print("loc assignment worked:", "status" in demo.columns)
print(demo[["price", "status"]])

loc assignment worked: True
    price status
o1   12.5    NaN
o2   30.0   high
o3    7.5    NaN
o4   22.0   high
o5   15.0    NaN
o6   40.0   high

## 🚀 Mini Project — Sales Explorer

In [7]:
orders = pd.DataFrame(
    {
        "order_id": ["A100", "A101", "A102", "A103", "A104", "A105", "A106", "A107"],
        "city": ["Berlin", "Paris", "Berlin", "Lisbon", "Paris", "Berlin", "Lisbon", "Paris"],
        "product": ["Widget", "Gadget", "Gizmo", "Widget", "Gadget", "Gizmo", "Gadget", "Widget"],
        "price": [12.5, 30.0, 7.5, 22.0, 15.0, 40.0, 18.0, 26.0],
        "units": [120, 45, 300, 80, 200, 15, 60, 25],
    }
)
orders

  order_id    city product  price  units
0     A100  Berlin  Widget   12.5    120
1     A101   Paris  Gadget   30.0     45
2     A102  Berlin   Gizmo    7.5    300
3     A103  Lisbon  Widget   22.0     80
4     A104   Paris  Gadget   15.0    200
5     A105  Berlin   Gizmo   40.0     15
6     A106  Lisbon  Gadget   18.0     60
7     A107   Paris  Widget   26.0     25

In [8]:
# Step 2 — whole row for one order by label.
orders.loc[orders["order_id"] == "A100"]

  order_id    city product  price  units
0     A100  Berlin  Widget   12.5    120

In [9]:
# Step 3 — positional slices and column selection.
print("last 3 rows:")
print(orders.iloc[-3:, [1, 3]])
print("\nfirst 4 rows:")
print(orders.iloc[:4, [1, 3]])

last 3 rows:
     city  price
5  Berlin   40.0
6  Lisbon   18.0
7   Paris   26.0

first 4 rows:
     city  price
0  Berlin   12.5
1   Paris   30.0
2  Berlin    7.5
3  Lisbon   22.0

In [10]:
# Step 4 — combined boolean filter.
big_orders = orders[(orders["price"] > 20) & (orders["units"] > 10)]
big_orders

  order_id    city product  price  units
1     A101   Paris  Gadget   30.0     45
3     A103  Lisbon  Widget   22.0     80
5     A105  Berlin   Gizmo   40.0     15
7     A107   Paris  Widget   26.0     25

In [11]:
# Step 5 — isin and between.
print("Berlin or Lisbon:")
print(orders[orders["city"].isin(["Berlin", "Lisbon"])][["order_id", "city"]])
print("\nPriced 10 to 30:")
print(orders[orders["price"].between(10, 30)][["order_id", "price"]])

Berlin or Lisbon:
  order_id    city
0     A100  Berlin
2     A102  Berlin
3     A103  Lisbon
5     A105  Berlin
6     A106  Lisbon

Priced 10 to 30:
  order_id  price
0     A100   12.5
1     A101   30.0
3     A103   22.0
4     A104   15.0
6     A106   18.0
7     A107   26.0

In [12]:
# Step 6 — tier via .loc assignment (CoW-safe).
orders.loc[orders["price"] >= 25, "tier"] = "premium"
orders.loc[orders["price"] < 25, "tier"] = "standard"
orders[["order_id", "price", "tier"]]

  order_id  price      tier
0     A100   12.5  standard
1     A101   30.0   premium
2     A102    7.5  standard
3     A103   22.0  standard
4     A104   15.0  standard
5     A105   40.0   premium
6     A106   18.0  standard
7     A107   26.0   premium

In [13]:
# Step 7 — derive revenue, sort, show top 3.
orders["revenue"] = orders["price"] * orders["units"]
top3 = orders.sort_values("revenue", ascending=False).head(3)
top3[["order_id", "city", "revenue"]]

  order_id    city  revenue
4     A104   Paris   3000.0
2     A102  Berlin   2250.0
3     A103  Lisbon   1760.0

In [14]:
# Step 8 — total revenue per city (full groupby arrives in Session 4).
orders.groupby("city")["revenue"].sum().sort_values(ascending=False)

city
Paris     5000.0
Berlin    4350.0
Lisbon    2840.0
Name: revenue, dtype: float64